# **ASSIGNMENT**

# **Theoretical Questions**

1. Purpose and Advantages of NumPy in Scientific Computing and Data Analysis
Purpose:

  NumPy (Numerical Python) is a library in Python that provides efficient and powerful tools for numerical computations. It forms the backbone of many scientific and data analysis workflows.

  Advantages:

  Efficient Storage: Uses contiguous memory blocks for storing data, making operations faster than Python lists.
  
  Vectorization: Eliminates the need for explicit loops by applying operations element-wise to entire arrays.
  
  Built-in Functions: Offers mathematical, logical, statistical, and Fourier transforms functions.
  
  Interoperability: Works seamlessly with other libraries like SciPy, Pandas, and Matplotlib.
  
  Support for Multi-dimensional Arrays: Easily handles multi-dimensional data structures.

2. Comparison: np.mean() vs np.average()

  Both functions compute the average of array elements but differ in functionality:
  
  np.mean():Calculates the arithmetic mean of elements. It treats all elements equally.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # Output: 2.5

2.5


np.average():
Allows weighted averages by specifying a weights parameter.

In [ ]:
weights = [1, 2, 3, 4]
print(np.average(arr, weights=weights))  # Output: 3.0

3.0


When to use: Use np.mean() for uniform averaging and np.average() for weighted contexts.

3. Reversing a NumPy Array
  
  1D Array:
  Reverse using slicing ([::-1]):

In [ ]:
arr = np.array([1, 2, 3, 4])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [4, 3, 2, 1]

[4 3 2 1]


2D Array:

  Reverse rows: arr[::-1, :]
  
  Reverse columns: arr[:, ::-1]

In [ ]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(arr_2d[::-1])   # Reverse rows
print(arr_2d[:, ::-1])  # Reverse columns

[[5 6]
 [3 4]
 [1 2]]
[[2 1]
 [4 3]
 [6 5]]


4. Determining Data Type in NumPy

  Use the .dtype attribute to determine the data type.

In [ ]:
arr = np.array([1.2, 3.4])
print(arr.dtype)  # Output: float64

float64


Importance:
  
  Memory Management: Data types like int32 or float64 define memory usage.
  
  Performance: Specific data types speed up numerical operations.

5. Defining ndarrays in NumPy

  Definition:
  An ndarray (N-dimensional array) is a fixed-size, multi-dimensional container for homogeneous data.

  Key Features:

    Supports element-wise operations.
  
    Efficient for large datasets.
  
    Has attributes like shape, size, dtype, and ndim.
  
  Difference from Python Lists:

  Arrays are faster and consume less memory.
  
  Arrays support broadcasting; lists do not.

6. Performance Benefits of NumPy Arrays Over Python Lists:
  
  Speed: NumPy arrays leverage optimized C implementations and vectorized operations.
  
  Memory Efficiency: Use a single data type for elements, avoiding Python's overhead.
  
  Batch Operations: Operate on entire datasets without loops.

In [ ]:
import numpy as np
arr = np.arange(1000000)
list_ = list(range(1000000))
%timeit arr * 2   # Faster
%timeit [x * 2 for x in list_]  # Slower

798 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
93 ms ± 24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


7. vstack() vs hstack()

  vstack(): Stacks arrays vertically.

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))

[[1 2]
 [3 4]]


hstack(): Stacks arrays horizontally.

In [ ]:
print(np.hstack((a, b)))

[1 2 3 4]


8. fliplr() vs flipud()

  fliplr(): Flips arrays horizontally.

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(np.fliplr(arr))

[[2 1]
 [4 3]]


  flipud(): Flips arrays vertically.

In [ ]:
print(np.flipud(arr))

[[3 4]
 [1 2]]


9. Functionality of array_split()
  
  Allows splitting arrays into sub-arrays. Handles uneven splits by varying sub-array sizes.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.array_split(arr, 3))

[array([1, 2]), array([3, 4]), array([5])]


10. Vectorization and Broadcasting in NumPy:
  
  Vectorization: Applies operations to entire arrays without loops.

In [ ]:
arr = np.array([1, 2, 3])
print(arr * 2)  # Output: [2, 4, 6]

[2 4 6]


Broadcasting: Automatically expands shapes for element-wise operations.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(a + b)

[[11 22]
 [13 24]]


Advantages: Reduces code complexity and improves computation speed.

# **Practical Questions**

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

array1 = np.random.randint(1, 101, (3, 3))
transposed_array1 = array1.T
print("Original 3x3 array:\n", array1)
print("Transposed array:\n", transposed_array1)

Original 3x3 array:
 [[73 17 10]
 [94 51 62]
 [97 72 63]]
Transposed array:
 [[73 94 97]
 [17 51 72]
 [10 62 63]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np

array2 = np.arange(10)
array2_2x5 = array2.reshape(2, 5)
array2_5x2 = array2_2x5.reshape(5, 2)
print("1D array:", array2)
print("2x5 array:\n", array2_2x5)
print("5x2 array:\n", array2_5x2)

1D array: [0 1 2 3 4 5 6 7 8 9]
2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it.

In [ ]:
import numpy as np

array3 = np.random.random((4, 4))
array3_with_border = np.pad(array3, pad_width=1, mode='constant', constant_values=0)
print("4x4 array:\n", array3)
print("Array with border:\n", array3_with_border)

4x4 array:
 [[0.9233668  0.01430489 0.68066311 0.43351654]
 [0.85300356 0.24212319 0.82677859 0.05018673]
 [0.874968   0.1696915  0.06822058 0.11708947]
 [0.9253063  0.14862794 0.77933228 0.11381926]]
Array with border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.9233668  0.01430489 0.68066311 0.43351654 0.        ]
 [0.         0.85300356 0.24212319 0.82677859 0.05018673 0.        ]
 [0.         0.874968   0.1696915  0.06822058 0.11708947 0.        ]
 [0.         0.9253063  0.14862794 0.77933228 0.11381926 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np

array4 = np.arange(10, 61, 5)
print("Array from 10 to 60 with step 5:", array4)

Array from 10 to 60 with step 5: [10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations.

In [ ]:
import numpy as np

array5 = np.array(['python', 'numpy', 'pandas'])
uppercase = np.char.upper(array5)
lowercase = np.char.lower(array5)
titlecase = np.char.title(array5)
print("Original array:", array5)
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title case:", titlecase)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word.

In [ ]:
import numpy as np

array6 = np.array(['python', 'numpy', 'pandas'])
spaced_array = np.char.join(' ', array6)
print("Original array:", array6)
print("Spaced array:", spaced_array)

Original array: ['python' 'numpy' 'pandas']
Spaced array: ['p y t h o n' 'n u m p y' 'p a n d a s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

array7_a = np.array([[1, 2], [3, 4]])
array7_b = np.array([[5, 6], [7, 8]])
addition = array7_a + array7_b
subtraction = array7_a - array7_b
multiplication = array7_a * array7_b
division = array7_a / array7_b
print("Array A:\n", array7_a)
print("Array B:\n", array7_b)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]
Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
import numpy as np

identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
print("5x5 Identity matrix:\n", identity_matrix)
print("Diagonal elements:", diagonal_elements)

5x5 Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements: [1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers.

In [ ]:
import numpy as np

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

array9 = np.random.randint(0, 1001, 100)
primes = np.array([num for num in array9 if is_prime(num)])
print("Original array:", array9)
print("Prime numbers:", primes)

Original array: [476 947 283  33 868 249 578 844 701 426  18 485 659 213 171 703 727 744
 629 594 857 923 425 592 597 992  77  29 215 358 611 154 549 234 926 918
 135 856 947 491 442 306 945 465  66 887 327 481 132  85 234  77 302 285
 662 271  95 270 466 680 112 135 223  48 281 189 528 302 338 902 489 613
 931  60 643 870 400 724  33 900 129  75 223 965 411 572 226 362 918 637
 786 556 810  53 808 932 100 382 197 716]
Prime numbers: [947 283 701 659 727 857  29 947 491 887 271 223 281 613 643 223  53 197]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
import numpy as np

# Generate daily temperatures for a 30-day month
temperatures = np.random.randint(20, 40, 30)  # Random temperatures between 20 and 40

# Reshape the array into 4 weeks of 7 days
temperatures_for_4_weeks = temperatures[:28].reshape(4, 7)  # Use only the first 28 days
weekly_averages = temperatures_for_4_weeks.mean(axis=1)

# Output results
print("Daily temperatures for the month (30 days):\n", temperatures)
print("Temperatures for 4 full weeks (28 days):\n", temperatures_for_4_weeks)
print("Weekly averages:", weekly_averages)


Daily temperatures for the month (30 days):
 [23 38 34 39 30 21 26 39 22 24 33 34 30 21 27 32 21 39 34 28 23 22 25 28
 28 38 38 30 37 35]
Temperatures for 4 full weeks (28 days):
 [[23 38 34 39 30 21 26]
 [39 22 24 33 34 30 21]
 [27 32 21 39 34 28 23]
 [22 25 28 28 38 38 30]]
Weekly averages: [30.14285714 29.         29.14285714 29.85714286]
